name: Deploy to WordPress.org
on:
  push:
    tags:
      - “*”
jobs:
  tag:
    name: WordPress.org Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        uses: 10up/actions-wordpress/dotorg-plugin-deploy@master
        env:
          THEMEBEEZ_GITHUB_TOKEN_WORKFLOW: ${{ secrets.GITHUB_TOKEN }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: simple-gdpr-cookie-compliance
